### ISSUE TITLE
Module breaks after DsN uptate

### ISSUE THREAD

**Issue by Gorka-de-Ituroitz** [brunocalado/swade-more-bennies#4]
After the recent DsN update the module does not work properly.
As soon as you select (almost) any Benny form the list all dices are hidden in the DsN configuration. You can roll and see the dice, but no 3D Benny is ever displayed.
The consle throws this error:
![image](https://github.com/user-attachments/assets/d6860e89-f85e-4026-a0e8-8dbc1fb664c5)

It seems it could be related with the 3D file, as the "Golden Snitch" and the "Shiedron" works, as well as a couple others I have added myself.

**Comment by brunocalado** [comment]
> After the recent DsN update the module does not work properly. As soon as you select (almost) any Benny form the list all dices are hidden in the DsN configuration. You can roll and see the dice, but no 3D Benny is ever displayed. The consle throws this error: ![image](https://private-user-images.githubusercontent.com/137724382/369862627-d6860e89-f85e-4026-a0e8-8dbc1fb664c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTQyNjYsIm5iZiI6MTcyNzA5Mzk2NiwicGF0aCI6Ii8xMzc3MjQzODIvMzY5ODYyNjI3LWQ2ODYwZTg5LWY4NWUtNDAyNi1hMGU4LThkYmMxZmI2NjRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjE5MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTU3NmU0MGVlMjVkNzBiZjU4YWE2ZWYyMmM5ODgxM2JlNmVmMjBiNmRkYmUxNDkzOWU4OWRlMjliN2U4OGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JIck_6WQl030PEfK0JeM1vszc1WzCBpi4L8ans7NBOs)
> 
> It seems it could be related with the 3D file, as the "Golden Snitch" and the "Shiedron" works, as well as a couple others I have added myself.

This is bad. I don't know what is causing this. I'll ask for help.

**Comment by brunocalado** [comment]
> After the recent DsN update the module does not work properly. As soon as you select (almost) any Benny form the list all dices are hidden in the DsN configuration. You can roll and see the dice, but no 3D Benny is ever displayed. The consle throws this error: ![image](https://private-user-images.githubusercontent.com/137724382/369862627-d6860e89-f85e-4026-a0e8-8dbc1fb664c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwOTQzMjUsIm5iZiI6MTcyNzA5NDAyNSwicGF0aCI6Ii8xMzc3MjQzODIvMzY5ODYyNjI3LWQ2ODYwZTg5LWY4NWUtNDAyNi1hMGU4LThkYmMxZmI2NjRjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QxMjIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTI1ODhmNjJiMzJjZTc5ZDFlODNhOWZiYzc5ZGVmMzNhMGU2M2I4M2U1YjI1NTcxYTRmYzMyMWEwZGM2NzZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OK9D_xJteNkwer4vBxjNO9lw8U9CvOwfVShDXee1h_c)
> 
> It seems it could be related with the 3D file, as the "Golden Snitch" and the "Shiedron" works, as well as a couple others I have added myself.

DsN dev will fix this issue. Just update DsN when the release is out.

**Comment by Gorka-de-Ituroitz** [comment]
Thank you.

**Comment by brunocalado** [comment]
> Thank you.

If DsN update don't fix call me again
